{
 "title": "Mongodb Dashboard",
 "description": "MongoDB Dashboard using Mongodb Exporter by percona for MongoDB deployed in Kubernetes (inspired by Opstree dashboard)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodb_up,app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up{app_kubernetes_io_instance=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoService UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{app_kubernetes_io_instance=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"current\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "stat",
   "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"totalCreated\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "opcounters",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "A document that reports on database operations by type since the mongod instance last started. These numbers will grow over time until next restart. Analyze these values over time to track database utilization."
   }
  },
  {
   "title": "Received Insert Operations",
   "type": "timeseries",
   "description": "The total number of insert operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"insert\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Update Operations",
   "type": "timeseries",
   "description": "The total number of update operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"update\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Command Operations",
   "type": "timeseries",
   "description": "The total number of commands issued to the database since the mongod instance last started.\n\nopcounters.command counts all commands except the write commands: insert, update, and delete.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"command\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Queries",
   "type": "timeseries",
   "description": "The total number of queries received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"query\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Delete Operations",
   "type": "timeseries",
   "description": "The total number of delete operations since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"delete\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received getMore Operations",
   "type": "timeseries",
   "description": "The total number of getMore operations since the mongod instance last started. This counter can be high even if the query count is low. Secondary nodes send getMore operations as part of the replication process.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"getmore\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Collections/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Indexs/DB",
   "type": "state-timeline",
   "description": "Total number of indexes across all collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexes{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Views/DB",
   "type": "state-timeline",
   "description": "Number of views in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "mongodb_dbstats_views{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}} "
    }
   ]
  },
  {
   "title": "Allocated Storage to Indexs in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all indexes in the database, including free index space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}